name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker login -u $USER -p $PASS; docker build . --file Dockerfile --tag chasepd/msfconsole:$(date +%s); docker push chasepd/msfconsole
